### ISSUE TITLE
Interchange (<dataset>, <cleanset_id>)

### ISSUE THREAD

**Issue by AshishSardana** [cleanlab/cleanlab-studio#144]
As per the API docs, in the `apply_corrections` method, the <cleanset_id> is the first argument and <dataset> second.
The following line in README has switched them - https://github.com/cleanlab/cleanlab-studio/blob/c25cce608db2cd985df593581f72a1c034b190ce/README.md?plain=1#L45

**Comment by jwmueller** [comment]
good catch! fixed in: https://github.com/cleanlab/cleanlab-studio/commit/708f8b0828521900be18ad8bca4fbe45283a50ca
