### ISSUE TITLE
Unable to get Cleanlab API

### ISSUE THREAD

**Issue by abhigyan631** [cleanlab/cleanlab-studio#160]
I am trying to do the Cleanlab Python API but can't get the API key.
It shows something like this even though I have signed up for the account by following the process given in the documentation.

<img width="353" alt="Screenshot 2023-12-21 104952" src="https://github.com/cleanlab/cleanlab-studio/assets/101783480/e6008130-f54e-4929-af8f-eb1f4b33eb07">

Please help me fix this issue, thanks a ton in advance.

**Comment by JacobGreen920** [comment]
Hi @abhigyan631, did you already fill out the [access request form](https://cleanlab.typeform.com/to/NLnU1XZF?typeform-source=cleanlab.ai)?

If so, could you let me know what email you used to sign up?

Thanks + apologies for the inconvenience you experienced in advance!

**Comment by abhigyan631** [comment]
Apologies, just saw the notification on Github, I created the account, and I got this as the message

"Success! Your account is being created! Expect a welcome email with login info from us in the next day :)"

Thank you.
