### ISSUE TITLE
Add Public Documentation for Image Support

### ISSUE THREAD

**Issue by aayushchhabra1999** [cleanlab/cleanlab-studio#51]
Add Instructions to use Cleanlab-Studio CLI to upload image datasets and how to run cleanlab against image datasets.

**Comment by aayushchhabra1999** [comment]
https://github.com/cleanlab/cleanlab-studio/pull/56

**Comment by aayushchhabra1999** [comment]
@anishathalye Assigning this over to you. The above PR has a lot of great feedback from Jonas. 
Lmk if you'd like me to incorporate the feedback in that PR.
Holding off on incorporating any feedback for now given the migration to sphinx docs.

**Comment by aayushchhabra1999** [comment]
@anishathalye Read the docs ready for launch?

**Comment by anishathalye** [comment]
For image support, I just wanted an updated README (which is done); RtD is for upcoming changes to the CLI (Python library).
